-keep class com.example.lynk.core.domain.** { *; }
-keep class ru.doGood.Lynk.** { *; }
-keep class * extends android.app.Application { *; }
-keep class dagger.hilt.** { *; }
-keepclassmembers class * implements java.io.Serializable { *; }
-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod
-dontwarn **